### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ShevchenkoEV** [ShevchenkoEV/testh#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>LANGUAGES</h3>
                            <p class="tags small">
                                <a href="assets/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa;
                                    <span>РУССКИЙ</span></a>
                                <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span>
                            </p>
                        </section>

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>SKILLS</h3>
                            <p class="tags small">NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING
                                INCORPORATING SELLING ADVERTISING HOSTING COMPETING TWITTING PARENTING GAMBLING DATING
                                SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIANING</p>
                        </section>

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>CHARACTER</h3>
                            <p class="tags small">ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS
                                IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL
                                LAZY SELF-PROMOTING</p>
                        </section>

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>LIKES&#x1f603;</h3>
                            <p class="tags small">
                                <a href="https://www.youtube.com/watch?v=u_aLESDql1U" rel="nofollow">BILLIONS</a>
                                FILET-O-FISH BIG MAC
                                <a href="https://www.youtube.com/watch?v=RDrfE9I8_hs" rel="nofollow">CHINA</a>
                                QUARTER POUNDER DIET COKE TARIFFS BIBLE ARTOF DEAL PATRIOTS BEAUTIFUL MODELS GOLD REAL
                                ESTATE WAR PROTESTERS CONSTRUCTION RUSSIANS BANKS SPORTS WOMEN MEXICO RED HAT KOREANS
                                GOLF EVERYBODY
                                <sup><a href="https://www.youtube.com/watch?v=0f9ysmciWUk" rel="nofollow">[1]</a> <a
                                        href="https://www.youtube.com/watch?v=TTdmKaXAfAs" rel="nofollow">[2]</a></sup>
                            </p>
                        </section>

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>Dislikes&#x1f61e;</h3>
                            <p class="tags small">
                                DOGS MEDIA CNN GERMANS MEXICANS IMMIGRANTS SHITHOLE COUNTRIES UNATTRACTIVE WOMEN BLACKS
                                SUSHI HOT-DOGS ALCOHOL FRUIT CHRISTMAS PARTIES LIBERALS</p>
                        </section>

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>WANTS&#x1f97a;</h3>
                            <p class="tags small bulleted">
                                BE HEALTHY GROW A TREE BUILD TRUMP AIRPORT HAVE A TASTE DO A HARLEM SHAKE IN CONGRESS TO
                                GOLF MORE OFTEN WIN ALL THE COURT SUITS</p>
                        </section>

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>EDUCATION</h3>
                            <ul class="timeline">
                                <li>
                                    <div><em>2011</em></div>
                                    <div><strong>Asked friends who are prominent and wealthy alumni of the New York
                                        Military Academy to secure my academic records so they could not be seen by
                                        anyone, never!</strong></div>
                                </li>
                                <li>
                                    <div><em>1966</em></div>
                                    <div><strong>Transferred to the Wharton School of the University of Pennsylvania and
                                        graduated in May 1968 with a B.S. in economics</strong></div>
                                </li>
                                <li>
                                    <div><em>1964</em></div>
                                    <div><strong>Started studying in Fordham University</strong></div>
                                </li>
                                <li>
                                    <div><em>1959</em></div>
                                    <div><strong>Enrolled in the New York Military Academy, a private boarding school,
                                        after my parents discovered I made frequent trips into Manhattan without their
                                        permission</strong></div>
                                </li>
                            </ul>
                        </section>

**Comment by alenagoodovanec** [comment]
<section>
                            <h3>MEDIA CAREER</h3>
                            <ul class="timeline">
                                <li>
                                    <p><em>2019 &#x2014</em></p>
                                    <p>Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9"</p>
                                </li>
                                <li>
                                    <p><em>2015 &#x2014</em></p>
                                    <p>Published a book "Crippled America: How to Make America Great Again"</p>
                                </li>
                                <li class="details">
                                    <input type="checkbox" id="event2011">
                                    <label for="event2011" class="summary"><em>2011 &#x2014 </em></label>
                                    <div>
                                        <ul>
                                            <li>Published a book "Time to Get Tough: Making America #1 Again" in coauthorship with Wynton Hall, Peter Schweizer and Meredith McIver</li>
                                            <li>Published a book "Midas Touch: Why Some Entrepreneurs Get Rich – And Why Most Don't" in coauthorship with Robert Kiyosaki</li>
                                            <li>Published a book "Trump Tower" in coauthorship with Jeffrey Robinson</li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <p><em>2009 &#x2014 </em></p>
                                    <p>Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver</p>
                                </li>
                                <li>
                                    <p><em>2008 &#x2014</em></p>
                                    <p>Published a book "Never Give Up: How I Turned My Biggest Challenges into Success" in coauthorship with Meredith McIver</p>
                                </li>
                                <li class="details">
                                    <input type="checkbox" id="event_2007">
                                    <label for="event_2007" class="summary"><em>2007 &#x2014 </em></label>
                                    <div>
                                        <ul>
                                            <li>Published a book "Think Big and Kick Ass" in coauthorship with Bill Zanker</li>
                                            <li>Received a star on the Hollywood Walk of Fame for being producer of Miss Universe pageant</li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="details">
                                    <input type="checkbox" id="event_2006">
                                    <label for="event_2006" class="summary"><em>2006 &#x2014 </em></label>
                                    <div>
                                        <ul>
                                            <li>Published a book "Why We Want You to Be Rich" in coauthorship with Meredith McIver and Robert Kiyosaki</li>
                                            <li>Published a book "How to Build a Fortune: Your Plan for Success From the World's Most Famous Businessman"</li>
                                            <li>Published a book "The Best Real Estate Advice I Ever Received: 100 Top Experts Share Their Strategies"</li>
                                            <li>Published a book "Trump 101: The Way to Success" in coauthorship with Meredith McIver</li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="details">
                                    <input type="checkbox" id="event_2005">
                                    <label for="event_2005" class="summary"><em>2005 &#x2014</em></label>
                                    <div>
                                        <ul>
                                            <li>Published a book "The Best Golf Advice I Ever Received"</li>
                                            <li>Performed a song with Megan Mullally at the 57th Primetime Emmy Awards</li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <p><em>2004 &#x2014  2008</em></p>
                                    <p>Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)</p>
                                </li>
                                <li class="details">
                                    <input type="checkbox" id="event_2004">
                                    <label for="event_2004" class="summary"><em>2004 &#x2014</em></label>
                                    <div>
                                        <ul>
                                            <li>Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver</li>
                                            <li>Published a book "The Best Golf Advice I Ever Received"</li>
                                            <li>Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver</li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <p><em>2003 &#x2014 2015</em></p>
                                    <p>Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"</p>
                                </li>
                                <li>
                                    <p><em>2000 &#x2014</em></p>
                                    <p>Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett</p>
                                </li>
                                <li>
                                    <p><em>1997 &#x2014</em></p>
                                    <p>Published a book "Trump: The Art of the Comeback" in coauthorship with Kate Bohner</p>
                                </li>
                                <li>
                                    <p><em>1991 &#x2014</em></p>
                                    <p>Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It"</p>
                                </li>
                                <li>
                                    <p><em>1990 &#x2014</em></p>
                                    <p>Published a book "Trump: Surviving at the Top" in coauthorship with Charles Leerhsen</p>
                                </li>
                                <li>
                                    <p><em>1987 &#x2014</em></p>
                                    <p>Published a book "Trump: The Art of the Deal" in coauthorship with Tony Shwartz</p>
                                </li>
                            </ul>
                        </section>
